theme: jekyll-theme-text
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
navbar:
  links:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"